# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='contenu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
