# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_auto_20160724_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
