# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0011_auto_20160725_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
