# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0014_auto_20160726_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lien',
            name='adresse',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
