# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0015_auto_20160726_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lien',
            name='lienhttp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
