# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profils', '0007_profil_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_message', models.IntegerField(blank=True, unique=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('id_topic', models.IntegerField(blank=True, unique=True)),
                ('date_dernier_message', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Sujet'),
        ),
    ]
