# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0003_auto_20160801_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
