# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0005_auto_20160801_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='img',
            field=models.ImageField(blank=True, upload_to='profil'),
        ),
    ]
