# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0006_auto_20160802_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
